### ISSUE TITLE
rename `mic configuration file` to `mic file`

### ISSUE THREAD

**Issue by sirspock** [mintproject/mic#107]

**Comment by Cmheidelberg** [comment]
@sirspock by 'mic configuration file' do you mean the constant `MIC_CONFIG_FILE_NAME` in constants or `--mic_config_file` option in main? Or both?

**Comment by dgarijo** [comment]
the mic configuration file term is ambiguous, so we need to rename all of them.

**Comment by dgarijo** [comment]
@sirspock In my latest run, this was already changed.
![image](https://user-images.githubusercontent.com/1520666/83475023-49224180-a442-11ea-8fb7-c0331c682f82.png)
