### ISSUE TITLE
Improve message step3

### ISSUE THREAD

**Issue by sirspock** [mintproject/mic#115]
Change MINT ->MIC
MIC Wrapper is the directory
MIC Run is the run

~/tmp/swat_precipitation_rates on master !1 ?4 ❯ mic encapsulate step3                                                                              Py dame
The MINT Wrapper has created: /Users/mosorio/tmp/swat_precipitation_rates/src/run

**Comment by sirspock** [comment]
@Cmheidelberg is it done?

**Comment by Cmheidelberg** [comment]
Yes, this will be included in my pr from the improved-outputs branch. I have a few more things I want to polish, then I will test and push code
