### ISSUE TITLE
MIC step 6 fails in Windows due to windows paths

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#120]
When doing tests 
```bash
 ./run   -i1 export_test\data\config.yml  -o1 config_yml.yml -o2 config_yml_bk.bk  -p1 Subsidy
```
Apparently mic writes paths assuming the component will be executed in Windows. However, the component will be executed inside a docker image in Unix, and hence the paths are wrong. Paths for the invocation should be generated assuming a Unix infrastructure.

@Cmheidelberg please address this issue as soon as you can, so we can define components in Windows too.

**Comment by dgarijo** [comment]
And we should add tests for this!

**Comment by sirspock** [comment]
The next version is not to be affected by this problem. We can ignore it.

**Comment by dgarijo** [comment]
Ok, we will close this issue when the next version is done. @Cmheidelberg please do not work on it.
