### ISSUE TITLE
allow adding multiple simple resources

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#16]
Right now we can add multiple complex resources such as authors, but not simple resources such as multiple categories, multiple descriptions, etc.

I think a good behavior would be the following:
`Select the property to [add,edit] [1-16] or [show, save, send, load, exit] [1]: add 11`

```
Adding new Category
Definition: Category associated with the model (e.g., Hydrology)
Model - Category  []:
```

**Comment by dgarijo** [comment]
It would be either this or before entering in editing mode, ask if you want to add resources or delete resources.

**Comment by sirspock** [comment]
Category is not an object property then it cannot be complex.

**Comment by sirspock** [comment]
One solution:
In the model catalog, the range of sdm:hasModelCategory is a new class: Category

**Comment by dgarijo** [comment]
Category is not complex. But it should be an array, not just a string (which is the way it's treated now anyway). Your solution is not valid, because I can have multiple descriptions or multiple licenses, or multiple documentation URLs (potentially). None of these are classes

**Comment by sirspock** [comment]
The range is string
https://mintproject.github.io/Mint-ModelCatalog-Ontology/release/1.4.0/index-en.html#hasModelCategory

**Comment by dgarijo** [comment]
Not complex, but multiple value. I want to have multiple categories.

**Comment by sirspock** [comment]
Maybe, we can define classes to avoid the bad practice.
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/2365990/78701450-e9813d00-78bb-11ea-8946-277d356cc290.png">

**Comment by dgarijo** [comment]
Again, these are not classes! These are strings. It's just that you can have multiple strings the same way that you can have multiple authors.

**Comment by sirspock** [comment]
I cannot understand the workflow of it. Can you work on it?

**Comment by dgarijo** [comment]
Starting point:
```
+-------+----------------+-----------------+
|    11 | Category       | ['Agriculture'] |
+-------+----------------+-----------------+
```
I need an `add` option:
```
Select the property to edit [1-17] or [show, save, send, load, exit] [1]: 11
Categories are:
- 'Hydrology',
Select action:  (add, edit, delete) [select]: add
Current value for Category is: None
Definition: Category associated with the model (e.g., Hydrology)
Model - Category  []: Hydrology
```
Result:
```
+-------+----------------+---------------------------------+
|    11 | Category       | ['Agriculture', 'Agriculture'] |
+-------+----------------+---------------------------------+
```
We don't need to have this for every simple resource, but we should support it for some

**Comment by sirspock** [comment]
And how do you save in the model catalog?

**Comment by sirspock** [comment]
Forget it. I understood.

**Comment by sirspock** [comment]
Well, I need to work on OBA. So, I dont want the issue.

**Comment by dgarijo** [comment]
this leads to 2 triples:
:targetModel hasCategory 'Agriculture'.
:targetModel hasCategory 'Hydrology'

This is the same as happens with other properties, right?

**Comment by sirspock** [comment]
Sorry, what is happening with the keywords?
https://rdfexplorer.mint.isi.edu/page/okn/i/mint/hand_v2_travis

![image](https://user-images.githubusercontent.com/2365990/78703510-27339500-78bf-11ea-84f4-728e0a1657bc.png)

Why are we using the semicolon (;)?

**Comment by dgarijo** [comment]
In this case, it was because the property is defined this way in schema.org: The property is called "keywords": I quote: "Keywords or tags used to describe this content. Multiple entries in a keywords list are typically delimited by commas". I used semicolon instead.
