### ISSUE TITLE
Mic gives all parameters the same position in the KG

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#162]
See https://rdfexplorer.mint.isi.edu/page/okn/i/mint/c56c4034-126a-4ec3-a861-ea2857ce65e1
All parameters have the same position (6), which is not correct. Since this configuration was created automatically, there must be an error in MIC.

**Comment by sirspock** [comment]
fixed it 

https://rdfexplorer.mint.isi.edu/page/okn/i/mint/d0877455-af90-4282-b9aa-a4fd8890fe37
