### ISSUE TITLE
Detect common code extension files as code

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#199]
In my java image, MIC asked me if the jar (which I literally executed) was code or not.

In my python image, MIC asked me if my python script was code or not.

I think that we could add a simple heuristic here: files that are `.jar`, `.py` and other common programming languages, let's detect them as code automatically.

**Comment by sirspock** [comment]
There is a method called: get_framework(mic_path). This returns the framework used it by the model

List of the framework supported by mic
https://github.com/mintproject/mic/blob/develop/src/mic/constants.py#L71

**Comment by dgarijo** [comment]
Oh, that's weird because it asked me if my jar/py files where part of the input

**Comment by sirspock** [comment]
My last comment was an advice to @Cmheidelberg. The issue is valid.

The step1 detects the framework and saves the information in the mic.yaml using the key: framework.
Chris can use the method `get_framework` to obtain it.

**Comment by mosoriob** [comment]
This is working.
