### ISSUE TITLE
[Discussion] MIC asks me if something is code, but does not ask if I want to expose an input

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#200]
This is a question to discuss, maybe to incorporate changes in the next version.

Right now `mic encapsulate inputs` asks me whether certain files are code or not. However, it does not ask me whether I want to expose the files or not. My question is:

Should we ask:

`Is <filename>a program or code?`

or

`Do you want to expose <filename> as an input`?

If the first question is necessary, we may need to ask the second one.

**Comment by mosoriob** [comment]
We are not supporting this type of communication with the user.
If something is wrong, they can edit the mic file.
