### ISSUE TITLE
When publishing, show the URL of the model configuration

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#201]
Right now the id is shown, but not the URL. I don't know where my component has gone (the `dame run` command helps a lot, but it's not enough)

**Comment by sirspock** [comment]
@hvarg The URL must be mint.isi.edu because models.mint.isi.edu doesn't show user resources.
Do you agree?
https://mint.isi.edu/ethiopia/models/configure/a48d5124-5b79-4ad2-b3e0-730ae07e36d1/4f136757-87e8-4b43-a387-9e89d3600f73/d0877455-af90-4282-b9aa-a4fd8890fe37
