### ISSUE TITLE
Shorten commands

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#215]
Encapsulate is descriptive, but it takes too long to write.

I would like to have a shorted version. Proposal:

```
mic enc start
mic enc trace
mic enc inputs
...
```
Or even shorter:

```mic -e start```

**Comment by dgarijo** [comment]
To discuss with @sirspock AFTER June release

**Comment by Cmheidelberg** [comment]
I think we could get rid of encapsulate completely. Just use `mic start` `mic trace` ext. Since we are already moving towards removing the `model` command there wont be clutter or confusion

**Comment by dgarijo** [comment]
I think then it gets confusing, because you have commands like `credentials` which are not used for the encapsulation process. I would still like to keep  model for now. Maybe calling it metadata or something like that. But that's another discussion

**Comment by sirspock** [comment]
mic pkg?

**Comment by sirspock** [comment]
mic zip

**Comment by dgarijo** [comment]
I like pkg because you are converting your component in a package in a way. Maybe we can discuss it with Yolanda.
mic zip I do not like because it's misleading.

**Comment by sirspock** [comment]
Ok. `pkg` is going to be.
