### ISSUE TITLE
After publish, DAME command is wrong

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#217]
**Describe the bug**
I successfully used mic to publish a component, but the command shown by DAME is incorrect:
```
Your Model Component has been published
Success
You can run the Model using DAME
dame run 50c9168b-da2b-4515-84ad-17d9e144b9d6 -p default
```
It should have been 
```
dame run 50c9168b-da2b-4515-84ad-17d9e144b9d6 -p 1350
```
According to: https://rdfexplorer.mint.isi.edu/page/okn/i/mint/c2f3781c-b9c2-44df-b36b-2ca78ab6682a

It looks like a key is not correctly read.

**Comment by dgarijo** [comment]
Actually, now that I re-read it: does this mean that the `default` is the default value?

**Comment by sirspock** [comment]
-p means the profile of the credentials
```
dame run --help                                                                                                                     Py dame
Usage: dame run [OPTIONS] NAME

  Run a model configuration or model configuration setup

Options:
  -p, --profile <profile-name>
  -d, --data PATH
  --interactive / --non-interactive
  --help                          Show this message and exit.
```

**Comment by dgarijo** [comment]
I got confused because `p` was the parameter in my  model
