### ISSUE TITLE
Let users remove inputs/ outputs using the input/ output command

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/mic#246]
**Is your feature request related to a problem? Please describe.**
We have mic encapsulate input/ output because there is a chance reprozip will miss an input or output from the trace. There is also a chance reprozip will miss classify an i/o. We should support removing inputs/ outputs/ parameters from the mic.yaml from within the corresponding commands. Additionally a user could also accidentally add something as an input or simply wish to remove an i/o from their model. Adding a option that deletes unneeded i/o/p will help abstract manual edits to the yaml away from the user making the program more intuitive and user friendly 

**Describe the solution you'd like**
I suggest adding a option `-d/ --delete` to the `mic encapsulate inputs` `outputs` and `parameters` command so users can easily remove i/o/p without manually editing the mic.yaml

Example:
```
mic encapsulate inputs my_in_csv --delete
```

**Comment by mosoriob** [comment]
The user can edit the file. We're not going to add more options
