### ISSUE TITLE
When the user add a configuration, list the versions

### ISSUE THREAD

**Issue by sirspock** [mintproject/mic#26]
A configuration must be linked with a ModelVersion

```
mic modelconfiguration add

#the user fills the model configuration information

#the user select push
Select the version related to the new model configuration
[1] cycles v1
[2] hand v2

Select the number [1]
```

1. Get all the version https://github.com/mintproject/model-catalog-python-api-client/blob/master/docs/endpoints/SoftwareApi.md#softwares_get
2. The user selects the version
3. Get the version https://github.com/mintproject/model-catalog-python-api-client/blob/master/docs/endpoints/SoftwareApi.md#softwares_id_get
4. Post the model configuration  and get the id
5. Put the model version
```

Notes:
1. The model version must exist. Add an alert.

**Comment by dgarijo** [comment]
If the model does not exist we can create a very simple one by asking the name.
