### ISSUE TITLE
When using MIC on a tracked Github repo, MIC produces an exception on load

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#261]
**Describe the bug**
If the repository is already tracked by GitHub, MIC should detect and issue an error. At the moment, the application fails with an exception. 
We say in the instructions that MIC should not be executed on a tracked GitHub repository; but if the user does it, it should not fail with an exception but with an error.

**To Reproduce**
Apply MIC in a tracked GitHub repository. When done, do `mic pkg upload`. The program will fail.

**Expected behavior**
A warning/error stating that there is a conflict with GitHub repos.

**Comment by mosoriob** [comment]
That's is not correct.
If I'm modifying an existing version of the component, I'm using the repository is already tracked by GitHub,
