### ISSUE TITLE
MIC is not working in WINDOWS

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#266]
The latest version of mic (both 1.2.1 and develop) are not working in WINDOWS:

After doing: `mic encapsulate start` the program asks for my component name, downloads the image and then exists:

```Step 5/5 : ENTRYPOINT ["/set_umask.sh"]

 ---> Running in c195b4142723
 ---> df7a18f5d0f5
Successfully built df7a18f5d0f5
Successfully tagged example:latest

You are in a Linux environment Debian distribution
We detect the following dependencies.

- If you install new dependencies using `apt` or `apt-get`, remember to add them in Dockerfile mic\docker\Dockerfile
- If you install new dependencies using python. Before the step `upload` run

pip freeze > mic/docker/requirements.txt

Please, run your Model Component.
docker run --rm -ti         --cap-add=SYS_PTRACE         -v C:\Users\dgarijo\Desktop\192\java_model_clean:/tmp/mint         -w /tmp/mint example:latest
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

Version 1.2.0 (installed from pypi) does not have this issue.

**Comment by mosoriob** [comment]
Windows is writing the file using CRLF breaking line

> CR and LF are control characters, respectively coded 0x0D (13 decimal) and 0x0A (10 decimal).
> They are used to mark a line break in a text file. As you indicated, Windows uses two characters the CR LF sequence; Unix only uses LF and the old MacOS ( pre-OSX MacIntosh) used CR.

https://futurestud.io/tutorials/how-to-fix-exec-user-process-caused-no-such-file-or-directory-in-docker


Before coding, I recommend checking if mic is writing the files using CRLF 

1. Generate a new project
2. Check the format of each file. Especially the Dockerfile.
a. If the encoding is LF, open the file and verify the encoding

**Comment by dgarijo** [comment]
I checked and all files are written with CRLF:
In `/docker`:
```
Dockerfile:    ASCII text, with CRLF line terminators
entrypoint.sh: Bourne-Again shell script, ASCII text executable, with CRLF line terminators
```
in `/mic`:
```
data:     directory
docker:   directory
mic.yaml: ASCII text, with CRLF line terminators
src:      directory
```

**Comment by Cmheidelberg** [comment]
Its failing because of this line of code in the start command:  `-v {user_execution_directory}:/tmp/mint \`
which is creating the mismatching path separators from Daniel's error
```
docker run --rm -ti         --cap-add=SYS_PTRACE         -v C:\Users\dgarijo\Desktop\192\java_model_clean:/tmp/mint         -w /tmp/mint example:latest
```
`-v C:\Users\dgarijo\Desktop\192\java_model_clean:/tmp/mint`

Easy fix but I cant test on Linux (since there might be more code like this hidden)
