### ISSUE TITLE
String parameters in commands fail in components due to extra quotes.

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#288]
Bug detected originally by @brandomr

**Describe the bug**
I created a simple python component which takes a string parameter in the command line:

`python linemodel.py config.json --p "parameter dos"`

It just prints the --p parameter on the screen.

However, after declaring everything in the mic.yaml file: 
`python linemodel.py config.json --p ${p}`

When mic runs the component, there are errors:
```
./run   -i1 /tmp/mint/mic/executions/07_29_00_37_51/src/x.csv  -o1 y_csv.csv  -p1 10 -p2 "parameter dos"
+ pushd .
/tmp/mint/mic/executions/07_29_00_37_51/src /tmp/mint/mic/executions/07_29_00_37_51/src
+ python linemodel.py config.json --p '"parameterdos"'
Parameter d: 'Banana'
Parameter command line: "parameterdos"
+ popd
/tmp/mint/mic/executions/07_29_00_37_51/src
+ set +x
````

Mic added additional quotes around the parameter and removed the spaces, which is incorrect. Note that in the mic.yaml file the parameter does not appear with quotes.

**To Reproduce**
See attached component, it has all the details and the executions produced by mic.

**Expected behavior**
MIC should not add those double quotes if the parameter is already with quotes.
[mic.zip](https://github.com/mintproject/mic/files/4991869/mic.zip)

**Comment by mosoriob** [comment]
Fixed v1.3.3
