### ISSUE TITLE
In submenus, "exit" option should be "back"

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#29]
Otherwise it looks like you are exiting the app, but you are in reality you want to go back to the previous resource

**Comment by sirspock** [comment]
When you use the action: `save` in a submenu, the cli tries to save the subresource.
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/2365990/78814200-1fd5bf80-7983-11ea-9edc-49c4fcb5b8ab.png">
