### ISSUE TITLE
Param auto detector will detect "multiple words in quotes" as several parameters

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/mic#290]
**Describe the bug**
using an invocation like `./mycode.py "my params"` will produce a wrapper like `./mycode.py ${param1} {$param2}`

We need to detect items in quotes as only one parameter. ie: `./mycode.py ${param1}` from the above example

Additionally, dont detect items that start with '-' as parameters, many programs use hyphen command line options.

**Comment by mosoriob** [comment]
Fixed 1.3.3
