### ISSUE TITLE
improve the text

### ISSUE THREAD

**Issue by sirspock** [mintproject/mic#3]
For me, we are showing too many things
```
Select the property to edit (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, show, save, send, load, exit) [1]: 1
Current value for Name is: None
Insert new value (c to CANCEL)
Model - Name [DEFINITION : Name of the model] [REQUIRED]
:

```

**Comment by dgarijo** [comment]
Why is it too many? As a user, I need to know what the current value I am modifying is (the table will cut strings that are too long for readability). I need to cancel, and I need to know the definition of the field. Maybe we could remove the definition of the filed and only show it if requested. For example, if you type help --> We would show (c to CANCEL or h to HELP).

**Comment by dgarijo** [comment]
This now has less text. Can we close this issue?
