### ISSUE TITLE
Encoding issues lead to exceptions

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#302]
When I was testing MIC today we had some files encoded in ANSI that led to encoding errors when reading it in MIC.

These errors were shown as an exception instead of the program collecting it and showing it to me.

**Comment by mosoriob** [comment]
Fixed by the entrypoint

https://github.com/mintproject/mic/blob/ed79ed925139885da9b1bea6cae57d529eddbb91/src/mic/templates/entrypoint.sh#L4
