### ISSUE TITLE
mic in docker should be installed with the same version that the user has on their local machine

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/mic#319]
**Is your feature request related to a problem? Please describe.**
When the user starts mic the version in docker is the most recent by default. It should instead default to the version the user is running on their machine. 

This way there is no confusion why mic in the docker is working differently than the version on their machine. This will also make development that much easier

**Comment by mosoriob** [comment]
Now, we are installing MIC when the container starts. Then, mic is going be updated
