### ISSUE TITLE
Show doesn't show resources appropriately

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#32]
**Describe the bug**
Complex resources just show the JSON (I did a simple version first) instead of rendering the complex object labels. They should show the labels appropriately

**To Reproduce**
![image](https://user-images.githubusercontent.com/1520666/78819176-a8a42980-798a-11ea-9b3d-bea691e33268.png)

**Comment by maurya-rohit** [comment]
@dgarijo Do you want to render this as a table. I meant what exactly you mean by rendering complex objects labels.

**Comment by dgarijo** [comment]
I think this issue may have already been solved. Now the complex resources
such as author show fine

**Comment by maurya-rohit** [comment]
Yes, and also solving #53 will give us more clarity.
