### ISSUE TITLE
Component uploaded to the wrong API [see last messages in issue]

### ISSUE THREAD

**Issue by iperezx** [mintproject/mic#342]
**Describe the bug**
I have successfully encapsulate my model with MIC, but when I get I try to upload the encapsulate model, I get an error with github commit. 

**To Reproduce**
1. git clone https://github.com/iperezx/edge-plugins/tree/ai-gateway-demo
2. cd ~/edge-plugins/plugin-smokedetect
3. Encapsulate model with mic or see README https://github.com/iperezx/edge-plugins/tree/ai-gateway-demo/plugin-smokedetect#setup-for-mic 
4. Errors with `mic pkg upload`

**Expected behavior**

**MIC log file**
mic   commands.py        ERROR    Upload failed: failed to create commit: current tip is not the first parent
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mic/click_encapsulate/commands.py", line 687, in upload
    push(mic_config_path.parent, mic_config_path, name, profile)
  File "/usr/local/lib/python3.9/site-packages/mic/publisher/github.py", line 80, in push
    git_commit(repo)
  File "/usr/local/lib/python3.9/site-packages/mic/publisher/github.py", line 132, in git_commit
    repo.create_commit('refs/heads/master', author, author, "automated mic", tree, parents)
_pygit2.GitError: failed to create commit: current tip is not the first parent

**Desktop (please complete the following information):**
 - OS: OSX

**Additional context**
I think it expects to be in master branch based on the line it errors out: https://github.com/mintproject/mic/blob/2.0.0/src/mic/publisher/github.py#L132

It seems it is expected behavior so this might be a feature request if that is the case.

**Comment by dgarijo** [comment]
Not at the moment, sorry.
But you may copy all the mic component folder in a new untracked folder and
do just the publish part. That should work.

**Comment by iperezx** [comment]
Thanks Daniel, yeah I just copied it to an empty folder and it worked fine. It is here: https://github.com/iperezx/smoke-detection. 

It was suppose to upload to another instance of MINT (https://wifire.models.mint.isi.edu/home) but it upload to the one you guys owned: https://mint.isi.edu/texas/models/explore/766e837d-a477-4596-aac7-ada40c52302b/ebecf3ab-af98-4156-964f-760eb2ace83c/9c8bacf0-fb6c-48d5-bdf4-5b9080e5352e. I checked many times that I inputted the right server name. Here is the output of `mic list-credentials`:
[default]
   server: https://api.models.wildfire.mint.isi.edu/v1.7.0
   username: mint@isi.edu
   git_username: iperezx
   git_token:
   name: mint
   email: mint@isi.edu
   dockerhub_username: iperezx

Maybe an issue similar to the one I reported for dame (https://github.com/mintproject/dame_cli/issues/87)?

**Comment by dgarijo** [comment]
Thanks!
That looks like an error indeed. I am going to change the description of the issue.
@mosoriob @hvarg do you  know what is going on? It looks like even though the server is well configured, it's being uploaded the wrong API!

**Comment by mosoriob** [comment]
Thanks for the report. I'm going to review it today.

**Comment by iperezx** [comment]
Any update on this?

**Comment by mosoriob** [comment]
Hi Ismael

Sorry for the delay. We were removing the GitHub dependency and I forgot this issue.
The changes seem ok and we're going to release the new version.
