### ISSUE TITLE
Adding a default value in a parameter fails

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#49]
**Describe the bug**
The API expects a complex object, but it should be asking for simple things. 

To fix this, we have to check that the thing being described is not only "object", but something else. For example, if it's a "Person" -> show complex object. But if it's an "Object" then show the simple menu.

**Comment by dgarijo** [comment]
This happens in more fields than parameter value

**Comment by dhruvp-8** [comment]
@dgarijo can you send steps to reproduce the described bug?

**Comment by dgarijo** [comment]
`mic modelconfiguration add`
press 12 (parameters)
`add`
press 3 or 4
`add`
--> Error.
The way to fix this is similar to the way I fixed it for "Person website". You have to define that it's not a complex value.

**Comment by dgarijo** [comment]
Ideally what should happen by pressing 3 or 4 is that it should ask you for a simple value.
To solve this in a generic way, you should treat "object" as a simple resource when there is no more information about it. Basically, as a URL

**Comment by dhruvp-8** [comment]
@dgarijo @sirspock raised PR. Please review it. I also have another way to do this instead of doing try except. But I feel this snippet is much reliable.

**Comment by dgarijo** [comment]
I will let @sirspock review, but the solution is a little hackish. I would make sure that if something is an object but is not described in the spec, then it should be treated as a simple resource.

**Comment by dhruvp-8** [comment]
@dgarijo everytime if something is not an object it will raise AttributeError Exception. So, basically I catch the exception and treat it as a simple resource.

**Comment by dgarijo** [comment]
I did something like this for person, but introduced errors with the recursion. I will let @sirspock decide. In the meantime please continue with the other issues.
