### ISSUE TITLE
Feature: validate a model configuration

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#50]
Given a URL or a local folder, mic should validate that the component added in there passes a set of checks:
- [ ] Check that the component structure makes sense (src is there, there is a run script that can be invoked, etc.)
- [ ] Check that the I/O of the run script corresponds to the I/O in mic
- [ ] Check that there is a docker image declared

If the local code is ok, then suggest uploading it to a GitHub repo following the guidelines we are working on and do a release.

**Comment by dhruvp-8** [comment]
@dgarijo do I have to create a new command in mic to do so?

**Comment by dgarijo** [comment]
Yes, this will be under a new command "validate":
`mic validate PathTofolder` for example `mic validate .`

**Comment by dgarijo** [comment]
Note that we are validating but not uploading anything to GitHub.

**Comment by dgarijo** [comment]
@dhruvp-8 see the new Figure in readme.md. We will have a new command 
`mic component validate` that will validate a folder against a set of rules:
- The folder structure should have a `src` folder, a `data` folder and optionally a `Dockerfile` folder 
- There should be a json file with the component metadata description (by default we can call it component.json).
- The src folder should have at least a run script and an 'io.sh' file for initializing input/outputs. see https://github.com/mintproject/MINT-WorkflowDomain/tree/master/WINGSWorkflowComponents/economic-v7/src as an example. 
- The validation should make sure that the number of I/O and param are consistent with the metadata of "component.json". That is, if there are 3 params declared in the metadata, there should be at least $PARAMS3 used in the component.

This issue makes more sense after `mic component init` has been created, but can be advanced in parallel

**Comment by Cmheidelberg** [comment]
@dgarijo @dhruvp-8 What is the status of this issue? Has there been progress and is anyone working on it now?

**Comment by sirspock** [comment]
I'm going to close this issue. We have a validation.
