### ISSUE TITLE
Values get added to main menu instead of sub-menu

### ISSUE THREAD

**Issue by dhruvp-8** [mintproject/mic#53]
**Describe the bug**
When you add the values for author using a different route then the values are not being added to the sub-menu instead they are added to the main menu

**To Reproduce**
1. mic model add
2. Press 7
3. select
4. n
5. Press 1 and add resource
6. exit

The main menu has a field "Name" and the sub-menu also has a field "Name". As a result values get added to both the fields which is incorrect

**Expected behavior**
The bug is noticeable after Step-4 when `Select the property to edit [1-17]` shows [1-17] instead of [1-3]. 

**Screenshots**
![image](https://user-images.githubusercontent.com/20561757/80094904-e8871700-851b-11ea-98f6-9c964e330bfc.png)

**Comment by dgarijo** [comment]
This is because the recursive behavior is not working correctly. The system thinks you are in the top resource instead of the subresource. I had fixed this issue before, but maybe some new commits changed the behavior. This is important

**Comment by dgarijo** [comment]
I have been able to reproduce this, good catch! I think when you select "n" it goes in the wrong path.
