### ISSUE TITLE
New feature: initialize model configuration

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#55]
This feature, similar to what we have in WINGS, will help setting up a component (let's start assuming the component is installed in the target machine).

The command `mic component init` (it's for configurations) will:

1. Ask the user the type of component to create (e.g., python, perl, bash, etc. See WINGS for examples).
2. Ask the number of I/O.
3. Create the src, data and the appropriate files inside.
4. mic will initialize the description of a model configuration with the number if i/o and params.

Note that at some point we will have to request uploading the component to GitHub and do a release.

**Comment by sirspock** [comment]
I would like to do it.
