### ISSUE TITLE
Validation of Software image

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#59]
If not provided, MIC should request it. 
If the image exists, mic should detect:

- [x] Does the image use a tag or use the "latest"? If the latter, then MIC should issue a warning and tell you to use a version. 
- [ ] If a github repo is provided for the component, check that it has a release and at least a Dockerfile. ~
- [x] Validate docker file (valid yaml).

**Comment by sirspock** [comment]
- The version issue has been addressed.
- When mic builds the image, Docker validate the Dockerfile

**Comment by sirspock** [comment]
> If a github repo is provided for the component, check that it has a release and at least a
> Dockerfile. ~

We can validate the structure of the component by step

For example, step X needs

1. mic.yaml
2. data
3. src
4. docker

**Comment by sirspock** [comment]
I have created a new issue about the validation.
I'm going to close this issue.
