### ISSUE TITLE
Add helper functions in MIC to help creating a component

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#61]
When creating the component, MIC should provide a set of functions to help common tasks for manipulation. This issue depends on #55. Common operations include:

- Zipping/Unzipping of folders to extract file or transform output.
- Replace parameter value in file.
- Doing small parameter manipulations (e.g., increase/decrease of a parameter value (variation of previous point).

**Comment by sirspock** [comment]
Done.
Missing the task 3: **Doing small parameter manipulations (e.g., increase/decrease of a parameter value (variation of previous point).**

But this is not clear to me.

**Comment by dgarijo** [comment]
This refers to, for example, those cases we had in the economic model where rather than exposing a value of a table we are exposing how to increment/decrement the values in an input. 

For example, I expose `fertilizer increment` which is a percentage, but what it does is multiply a value of input X by `fertilizer increment`. I think this is not high priority, and maybe it should not be on MIC to perform (but it is a very interesting helper functionality)
