### ISSUE TITLE
Show metadata completeness levels

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#63]
Right now MIC shows only some metadata that is considered more important or critical for execution. MIC should guide users on 3 main metadata levels:

- Findability: detect which features are key for others to find a model.
- Execution: all metadata needed to execute a model.
- Understanding: all metadata fields needed to describe variables, etc. 

MIC should show the completeness on these levels (could be a percentage).

**Comment by sirspock** [comment]
MIC is going to work only on the execution level. This issue is handling by mint-ui
