### ISSUE TITLE
Metadata validation

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#65]
MIC should validate some basic metadata properties.
For example, URLs should be URLs, minimum value for parameters should be float, etc.

**Comment by dgarijo** [comment]
This is different from `mic component validate`. This issue makes sure that fields are properly initialized.

**Comment by maurya-rohit** [comment]
@dgarijo @sirspock We have created a generalized method to validate the input. Currently we have added checks only for "Download URL" and "minimum value" in parameter. We wanted to get your opinion on the approach. If you think it is the right way, we will add to other metadata as well. Please let us know. If you have any questions regarding the method, let us know and we will explain.

**Comment by dgarijo** [comment]
I think it looks good to me. Ideally it would be extracted from the API, but we had to remove literals for some other reasons, so I think the approach taken is correct.
The ony thing, I would do an enumerated type to know which number corresponds to which type, otherwise It's difficult to maintain. Do a pull request when ready please.

**Comment by maurya-rohit** [comment]
Yes, so we will add other types according to our understanding like website should be url and will add the checks for other values of float. We will inform you after that and let us know if you think we missed something where we should have added the validation.

**Comment by maurya-rohit** [comment]
Pull request has been raised.
