### ISSUE TITLE
Documentation [End of June]

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#68]
Generate documentation for the end of June release

**Comment by khider** [comment]
Note on documentation for steps 1-4. most can be addressed by fixing the example

1. Before you start:
a. No need to be in the same directory as the model
b. No need to be in the same conda environment as the libraries needed to run the model 

1.  Step 1: mention that the name of the model component is anything the user's chooses and doesn't have to match the name of the code file. 

2. Make clearer that config.file (if any) needs to be in the data folder. The example uses SWAT and mentions a file but never show it in the directory or in the mic.yaml file being generated.

3. Consistent naming: the example talks about `mic.yaml` in step 2 but then switched to `config.yaml` in step 3. 

4. Add more screenshots of expected results:
a. Step 2: show the yaml file and the resulting edit (as in step 3)

5. Step2/3/4: mention that cd into the model_component directory allows to use default -f command. 

6. The placeholders are not just for the parameters but also variable value files.

**Comment by dgarijo** [comment]
@khider I will work on these issues, but I want to make sure that this is consistent with the next version of mic. Some of these issues will disappear then.

**Comment by dgarijo** [comment]
I have updated the documentation based on the new version.
Now:
1. Doesn't apply because you can organize your files as you please.
2. Fixed.
3. N/A
4. Fixed
5. Added logs of expected results.
6. Fixed (now it is done automatically)
7. In theory MIC should do this automatically now. But just in case I added a note on inputs.
