### ISSUE TITLE
If a model name exists, notify the user

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#69]
MIC does not support model editing right now. If a model (or model configuration) is pushed with a label that is equal to an existing one, MIC should warn the user.

**Comment by dhruvp-8** [comment]
MIC should warn the user if label already exists. Should it still allow to push or terminate the process?

**Comment by dgarijo** [comment]
At the moment let's just issue a warning. Do not terminate the application, as the user may want to change the name of the label before trying to push again

**Comment by dhruvp-8** [comment]
I think there is some issue with my API username password. Is it possible for you to clear the graph for dhruvrpa@usc.edu username?

**Comment by dhruvp-8** [comment]
Please let me know if this approach is correct and I will open the PR

**Comment by dgarijo** [comment]
@sirspock can you please check this out?

**Comment by dgarijo** [comment]
In the meantime @dhruvp-8 please work on other issues
