### ISSUE TITLE
Define missing fields and classes (model config, etc.)

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#7]
We don't have the means to add new model configurations.
Ideally by typing `mic add modelConfig` or `mic add mc`

We have to copy the missing classes and properties

**Comment by sirspock** [comment]
The correct name is modelconfiguration, but it is long.

**Comment by dgarijo** [comment]
I agree. We could use the acronym:
mic add m --> Model
mic add mc --> ModelConfiguration
mic add mcs --> ModelConfigurationSetup

**Comment by dgarijo** [comment]
This is now possible, so I will close the issue for now
