### ISSUE TITLE
End-to-end example with model configuration

### ISSUE THREAD

**Issue by dgarijo** [mintproject/mic#73]
I would like an end-to-end model configuration with a hello world! component.  The example should be a json file defining a model configuration with 1 parameter, 1 input, 1 output and basic metadata.  The model configuration should be executable by DAME.
For the component, we can upload it somewhere on GitHub.

**Comment by dhruvp-8** [comment]
Can you explain in detail about what you mean by "executable by DAME"? Should we take an existing model configuration example or do you have any specific model in your mind?

**Comment by dgarijo** [comment]
DAME is a desktop application for model execution that allows you execute models from the model catalog in your local machine. See https://github.com/mintproject/dame_cli/

A very simple model executable could be a hello world example. However, we should test also with one of the existing models. For this issue we need Max to push his latest proposal for adding executables. Please give more priority to the other issues you have assigned.

**Comment by sirspock** [comment]
We have the first version of the documentation.
