### ISSUE TITLE
mic publish - git

### ISSUE THREAD

**Issue by sirspock** [mintproject/mic#77]
`mic modelconfiguration publish` is the final step of the `mic` pipeline
https://mic-cli.readthedocs.io/en/develop/model_configuration/07/

```bash
$ mic model_configuration push
Pushing image
Pushing Git repository
Pushing Model Configuration

URL Model Configuration
```

## Publishing the Git repository

You must implement the `publish_github` method and the related methods
The idea is to Publish the directory on Github.

The method `create_github_repository` creates a new repository using the personal account of the user (-we don't support organization-).

- [x] You must create documentation about to obtain the TOKEN and set up it. Please, use [github](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).  And the documentation must be in the `docs` directory.

- [x] [git_add] is `git add`
- [x] [git_commit] you can use a generic message
- [x] [git release] you query the releases of the github repository and increase it.
- [x] [git_push] is `git push -u origin master` 

You can use the `GitHub` branch

```
def publish_github(directory: Path):
    """
    Publish the directory on git
    If the directory is not a git directory, create it
    If the git directory doesn't have a remote origin, create a github repository
    @param directory:
    @type directory:
    """
    try:
        if not is_git_directory():
            git_init()
        if not is_has_remote_branch():
            create_github_repository()
        compress_src_dir()
        git_add()
        git_commit()
        git_release()
        git_push()

    except Exception as e:
        raise e

```

**Comment by Cmheidelberg** [comment]
@sirspock do you have anything against me storing GitHub credentials (username, token) in the .mint credentials profile?

**Comment by dgarijo** [comment]
@Cmheidelberg I think that's fine. Store them and if we need to change it later, we'll do
