### ISSUE TITLE
github push will fail if remote repository is ahead of local 

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/mic#88]
**Describe the bug**
Pygit2 throws this error if remote repo is different from local
`_pygit2.GitError: cannot push because a reference that you are trying to update on the remote contains commits that are not present locally`

**Expected behavior**
This might not be common enough to care about now, but this issue could come up under standard usage. 

**Screenshots**
Full traceback:
![image](https://user-images.githubusercontent.com/14925268/82599194-bab7e100-9b60-11ea-9adc-325871f6d696.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by sirspock** [comment]
- MIC must pull the changes.
- If there is a merge isn't clean, the user has three option:
1. Accept the master changes. `our`
2. Accept the local changes `theirs`
3. Exit and fix the changes.

https://www.pygit2.org/merge.html#pygit2.Repository.merge_commits

**Comment by sirspock** [comment]
Fixed in v1.0.1
