### ISSUE TITLE
mic encapsulation needs in depth documentation

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/mic#90]
There should be a documentation page for steps 1 - 9 in the `docs/` folder
- [x] step1: General documentation
- [x] step2: General documentation
- [x] step3: General documentation + describe what the wrapper is doing/ why it is needed 
- [x] step4: General documentation + give or link instructions on how to make a configuration_file
- [x] step5: General documentation + how does this test the model 
- [x] step6: General documentation + what does selecting language do? how does it affect the script down the line?
- [x] step7: General documentation
- [x] step8: General documentation
- [x] step9: General documentation

Steps 1 - 4 already have good documentation in the add modelconfiguration page, but creating a separate more detailed page for each of these steps is also needed.

**Comment by dgarijo** [comment]
@Cmheidelberg we do have dedicated pages for each step: https://mic-cli.readthedocs.io/en/latest/model_configuration/03-step1/. This is in fact the modelconfiguration folder you refer to. I think this issue can be closed, I am in the process of reviewing each step separately, and we have opened issues for them like #68
