### ISSUE TITLE
Discussion: What is the best way to ask the parameters?

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/mic#92]
A couple minor feature requests for step2:

- [ ] The user should be given some way to enter the name and type of the parameters from within mic. That way they dont have to manually change it after. This would also let mic validate the parameter so they dont accidentally use an invalid name (A name with white spaces or the same name twice)
- [x] No default value should be assigned to a parameter. At the moment each parameter seems to be given a random value (bool, double, string). This might be confusing to a user
- [ ] According to the current docs the user is expected to copy over their inputs to the data/ folder. step2 could output a warning if the data/ folder is empty since the user could have accidentally skipped that step.

**Comment by sirspock** [comment]
```
mic encapsulate stepX --number_parameters 4
mic encapsulate stepX --color blue --animal elephant --friend rabbit --color--friend red
```

I propose two option. I like the second option.

**Comment by dgarijo** [comment]
Good question. I like 1 because it is easier. I also like 2 because it is direct; however the problem with 2) is that if I mess up and I want to do it later, I have to list parameters again. Can we support both?

Later on, I think we should have a third option: `mic encapsulate stepX --add_parameter --time_step 0`, which appends other parameter[s] to an existing mic yaml file. That way if I remember that I forgot to add one I can do it easily.

**Comment by sirspock** [comment]
I like the third option. I think it must be a unique way to add parameters using the CLI (the user can edit the parameter editing the mic file) 

```
mic encapsulate stepX --list_parameter
#Maybe in the future
mic encapsulate parameters --add
mic encapsulate parameters --list
```

Do we agree with it?

**Comment by dgarijo** [comment]
So the workflow would be something like:

`mic encapsulate parameters --list`

No parameters specified

```
mic encapsulate parameters --add --friend rabbit
mic encapsulate parameters --list
```
parameter: friend

Is this accurate?

This workflow works better if you like working with the terminal. However, supporting `--number_parameters 4` is nice for those who want to go to the mic.yaml file and edit the parameters. What do you think?
