### ISSUE TITLE
Encapsulate step4 ValueError 

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/mic#93]
**Describe the bug**
When running `mic encapsulate step4 config.yaml data/myConfig.con` step4 would crash with `ValueError: C:\\users\\...\\micStepTest\\config.yaml does not start with C:\\users\\...\\micStepTest\\data`. In this case myConfig.con was just filled with junk configuration data but im guessing this is a path issue.

**Screenshots**
Full error:
![image](https://user-images.githubusercontent.com/14925268/82956336-6ef0a780-9f65-11ea-8d17-8ce048149fe7.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by sirspock** [comment]
This is a user error. 

In the step 4, the user must add the configuration file of the model. 

You are adding the mic.yaml.

**Comment by dgarijo** [comment]
Let's close this issue then
