### ISSUE TITLE
Encapsulation validation

### ISSUE THREAD

**Issue by Cmheidelberg** [mintproject/mic#94]
Each step for encapsulation should have some form of validation to check if the user has a correct configuration before it runs. This would prevent hard crashes and help to inform the user what is wrong with their configuration if they have messed up. 
Things to check for:
- step2: output warning if data/ folder empty since user may have skipped copying their inputs over
- step3: validate parameter names are valid (no whitespace or duplicate names)
- step5, 7 and 8 all crashed for me. Though I didnt have a model to upload so this was likely caused by me. But validation on these steps would help the user find out what they are doing wrong 
- step9 this is probably the most important one to validate for because if the configuration is misconfigured then the model could be half published before the program hard crashes which would cause issues.

**Comment by sirspock** [comment]
Let's start with this:
https://github.com/mintproject/mic/issues/130
